### ISSUE TITLE
Function does not exist

### ISSUE THREAD

**Issue by Purus** [antecedent/patchwork#47]
I am trying  to patch the function send() present in the BOL_MailService class. I am using the below code for the same.

```
require_once $classDir . DS . "vendor" . DS . "autoload.php";
require_once $classDir . DS . "vendor" . DS . 'antecedent/patchwork/Patchwork.php';
require_once $classDir . 'logs.php';
```

```
//logs.php
Patchwork\redefine("BOL_MailService::send", function(BASE_CLASS_Mail $mail) {
    printVar($mail);
});
```

The below is the JSON file.

```
{
    "redefinable-internals": [
        "BOL_MailService::send"
    ]
}
```

I have tried the below format too.

`array('BOL_MailService', 'send')`

I get the below exception. I assume that the json method name should be modified to match the callable signature. Any help on the same?

```
Message:	Function send() does not exist
File:	C:\ow_plugins\email_logs\classes\vendor\antecedent\patchwork\src\CallRerouting.php
Line:	363

Trace:	
#0 C:\ow_plugins\email_logs\classes\vendor\antecedent\patchwork\src\CallRerouting.php(363): ReflectionFunction->__construct('send')
#1 C:\ow_plugins\email_logs\classes\vendor\antecedent\patchwork\Patchwork.php(131): Patchwork\CallRerouting\createStubsForInternals()
#2 C:\ow_plugins\email_logs\init.php(28): require_once('C:\..')
#3 C:\ow_system_plugins\base\bol\plugin_service.php(684): include_once('C:\...')
#4 C:\ow_core\plugin_manager.php(133): BOL_PluginService->includeScript('C:\...')
#5 C:\ow_core\plugin_manager.php(104): OW_PluginManager->initPlugin(Object(OW_Plugin))
#6 C:\ow_core\application.php(128): OW_PluginManager->initPlugins()
#7 C:\index.php(54): OW_Application->init()
#8 {main}
```

**Comment by antecedent** [comment]
The `redefinable-internals` key in `patchwork.json` is only needed for internal functions like `time()`.

**Comment by Purus** [comment]
Got it.. My bad.

I am using the below code and it seems that there is no effect of it.

```
Patchwork\redefine(array("BOL_MailService","send"), function(BASE_CLASS_Mail $mail) {
    printVar($mail);
});
```

**Comment by antecedent** [comment]
This is strange.

Try swapping the includes:

```php
require_once $classDir . DS . "vendor" . DS . 'antecedent/patchwork/Patchwork.php';
require_once $classDir . DS . "vendor" . DS . "autoload.php";
require_once $classDir . 'logs.php';
```

If that doesn't help, could you add an extra debug statement and post the output (a boolean):

```php
require_once $classDir . DS . "vendor" . DS . 'antecedent/patchwork/Patchwork.php';
require_once $classDir . DS . "vendor" . DS . "autoload.php";
require_once $classDir . 'logs.php';
var_dump(Patchwork\hasMissed('BOL_MailService::send'));
```

**Comment by Purus** [comment]
I have tried the debug statement. It returns false.

I have tried both BOL_MailService::send and array("BOL_MailService", "send")

**Comment by Purus** [comment]
It's all right now. It was my mistake. The code works fine now. Sorry for all the trouble. I guess it's a bad day for me :)

**Comment by Purus** [comment]
Looks it's issue wiht my code. After debugging I found the issue and fixed. It's not related to Patchwork.

Thanks for time.

I guess I am having a bad day.
