### ISSUE TITLE
" phpunit --version" return Uncaught ReflectionException: Class PHPUnit\Runner\VersionId

### ISSUE THREAD

**Issue by nocttuam** [antecedent/patchwork#71]
Hi @antecedent,

I have this error running the command: `phpunit --version`
````
PHP Fatal error:  Uncaught ReflectionException: Class PHPUnit\Runner\VersionId does not exist in /vendor/antecedent/patchwork/src/CallRerouting.php:528
Stack trace:
#0 /vendor/antecedent/patchwork/src/CallRerouting.php(528): ReflectionClass->__construct('PHPUnit\\Runner\\...')
#1 /vendor/phpunit/phpunit/src/Runner/Version.php(35): Patchwork\CallRerouting\dispatchInstantiation('PHPUnit\\Runner\\...', 'PHPUnit\\Runner\\...', Array)
#2 /vendor/phpunit/phpunit/src/Runner/Version.php(61): PHPUnit\Runner\Version::id()
#3 /vendor/phpunit/phpunit/src/TextUI/Command.php(1056): PHPUnit\Runner\Version::getVersionString()
#4 /vendor/phpunit/phpunit/src/TextUI/Command.php(593): PHPUnit\TextUI\Command->printVersionString()
#5 /vendor/antecedent/patchwork/src/CallRerouting.php on line 528
````

Package version: 2.1.4
PHP version: 7.0.22
PHPUnit version: 6.3.0

I do not have any written code, I just run the mentioned command.

**Comment by nocttuam** [comment]
Thank you. This commit resolve the phpunit bug and a bug with  [Robo](http://robo.li/)
