### ISSUE TITLE
Breaking PHPStan

### ISSUE THREAD

**Issue by ondrejmirtes** [antecedent/patchwork#74]
Hi,
I'm investigating an issue reported at https://github.com/phpstan/phpstan/issues/454 and we've tracked it down to Patchwork. Somehow, the current stable version 2.1.5 breaks on following code:

```php
public function createService__8(): PHPStan\Reflection\FunctionReflectionFactory
	{
		// here
		return new class ($this) implements PHPStan\Reflection\FunctionReflectionFactory {
			private $container;


			public function __construct(Container_7a918bd1d3 $container)
			{
				$this->container = $container;
			}


			public function create(ReflectionFunction $reflection, array $phpDocParameterTypes, PHPStan\Type\Type $phpDocReturnType = null): PHPStan\Reflection\FunctionReflection
			{
				$service = new PHPStan\Reflection\FunctionReflection($reflection, $this->container->getService('32'),
					$this->container->getService('6'), $this->container->getService('28'), $phpDocParameterTypes,
					$phpDocReturnType);
				return $service;
			}
		};
	}
```

(The code itself is from a generated DI container by `nette/di`).

It reports:

```
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting ';' in /private/var/folders/3f/222jf7lx5y96px53wkcj9r0w0000gn/T/phpstan/cache/Nette.Configurator/Container_7a918bd1d3.php on line 341

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting ';' in /private/var/folders/3f/222jf7lx5y96px53wkcj9r0w0000gn/T/phpstan/cache/Nette.Configurator/Container_7a918bd1d3.php on line 341
```

I found out that if I comment out these two lines in Patchwork.php, it starts working:

```php
CodeManipulation\register([
    CodeManipulation\Actions\CodeManipulation\propagateThroughEval(),
    CodeManipulation\Actions\CallRerouting\injectCallInterceptionCode(),
    //CodeManipulation\Actions\CallRerouting\injectQueueDeploymentCode(),
    CodeManipulation\Actions\RedefinitionOfInternals\spliceNamedFunctionCalls(),
    CodeManipulation\Actions\RedefinitionOfInternals\spliceDynamicCalls(),
    //CodeManipulation\Actions\RedefinitionOfNew\spliceAllInstantiations,
    CodeManipulation\Actions\RedefinitionOfNew\publicizeConstructors,
    CodeManipulation\Actions\ConflictPrevention\preventImportingOtherCopiesOfPatchwork(),
]);
```

Interestingly, if I update to current dev-master, it breaks on a different, possible unrelated issue:

```php
PHP Fatal error:  Uncaught TypeError: ArrayIterator::__construct() expects parameter 3 to be a class name derived from Iterator, '' given in /Users/ondrej/Downloads/phpstan-reproduce/vendor/antecedent/patchwork/src/CallRerouting.php(537) : eval()'d code:1
Stack trace:
#0 /Users/ondrej/Downloads/phpstan-reproduce/vendor/antecedent/patchwork/src/CallRerouting.php(537) : eval()'d code(1): ArrayIterator->__construct(Array, NULL, '')
#1 /Users/ondrej/Downloads/phpstan-reproduce/vendor/symfony/console/Helper/HelperSet.php(111): Patchwork\Instantiators\ArrayIterator->instantiate(Array)
#2 /Users/ondrej/Downloads/phpstan-reproduce/vendor/symfony/console/Application.php(881): Symfony\Component\Console\Helper\HelperSet->getIterator()
#3 /Users/ondrej/Downloads/phpstan-reproduce/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/ondrej/Do in /Users/ondrej/Downloads/phpstan-reproduce/vendor/antecedent/patchwork/src/CallRerouting.php(537) : eval()'d code on line 1
```

But commenting out the same lines also helps.

Feel free to contact me if you need any help reproducing this. Thanks.

**Comment by antecedent** [comment]
Thanks for the report; could you retry with the current `dev-master` after the latest commit?

**Comment by mundschenk-at** [comment]
@antecedent @ondrejmirtes Since the original report came from me, I've tried again in a live environment with the latest `deve-master` and everything seems to work now.

**Comment by ondrejmirtes** [comment]
I confirm that it now works! Great job!
